var ev = {
		"1" : {"descricao" : "Abandono_Main", "reason" : "Abandono Main"},
		"2" : {"descricao" : "Inicio_Europ_Amex", "reason" : "Inicio Europ Amex"},
		"3" : {"descricao" : "Inicio_Coleta_Cartao", "reason" : "Inicio Coleta Cartao"},
		"4" : {"descricao" : "Cartao_Invalido", "reason" : "Cartao Invalido"},
		"5" : {"descricao" : "Cartao_Valido", "reason" : "Cartao Valido"},
		"6" : {"descricao" : "Cliente_Perfil_1", "reason" : "Cliente Perfil 1"},
		"7" : {"descricao" : "Cliente_Perfil_2", "reason" : "Cliente Perfil 2"},
		"8" : {"descricao" : "Cliente_Perfil_3", "reason" : "Cliente Perfil 3"},
		"9" : {"descricao" : "Transferencia_Operador_Express_Fun", "reason" : "Transferencia Operador Express Fun"},
		"10" : {"descricao" : "Erro_Armazena_Protocolo", "reason" : "Erro Armazena Protocolo"},
		"11" : {"descricao" : "Abandono_Perfil_1", "reason" : "Abandono Perfil 1"},
		"12" : {"descricao" : "Inicio_Perfil_1", "reason" : "Inicio Perfil 1"},
		"13" : {"descricao" : "Opc_Central_Atendimento_Perfil_1", "reason" : "Opcao Central de Atendimento Perfil 1"},
		"14" : {"descricao" : "Opc_Solicitacao_Assistencia_Perfil_1", "reason" : "Opcao Solicitacao Assistencia Perfil 1"},
		"15" : {"descricao" : "Opc_Concierge_Perfil_1", "reason" : "Opcao Concierge Perfil 1"},
		"16" : {"descricao" : "Opc_Solicitacao_Schengen_Perfil_1", "reason" : "Opcao Solicitacao Carta Schengen_Perfil_1"},
		"17" : {"descricao" : "Repetir_Opcoes_Perfil_1", "reason" : "Repetir Opcoes Perfil 1"},
		"18" : {"descricao" : "Erro_Captura CVV", "reason" : "Erro Captura CVV"},
		"19" : {"descricao" : "Opc_Invalida_Perfil_1", "reason" : "Opcao Invalida Perfil 1"},
		"20" : {"descricao" : "Tempo_Espera_Excedido_Perfil_1", "reason" : "Tempo de Espera Excedido Perfil_1"},
		"21" : {"descricao" : "Abandono_Perfil_2", "reason" : "Abandono Perfil 2"},
		"22" : {"descricao" : "Inicio_Perfil_2", "reason" : "Inicio Perfil 2"},
		"23" : {"descricao" : "Opc_Central_Atendimento_Perfil_2", "reason" : "Opcao Central Atendimento Perfil 2"},
		"24" : {"descricao" : "Opc_Assistencia_Perfil_2", "reason" : "Opcao Assistencia Perfil 2"},
		"25" : {"descricao" : "Opc_Reserva_Restaurante_Perfil_2", "reason" : "Opcao Reserva Restaurante Perfil 2"},
		"26" : {"descricao" : "Opc_Express_Fun_Perfil_2", "reason" : "Opcao Express Fun Perfil 2"},
		"27" : {"descricao" : "Repetir_Opcoes_Perfil_2", "reason" : "Repetir Opcoes Perfil 2"},
		"29" : {"descricao" : "Opc_Invalida_Perfil_2", "reason" : "Opcao Invalida Perfil 2"},
		"30" : {"descricao" : "Tempo_Espera_Excedido_Perfil_2", "reason" : "Tempo Espera Excedido Perfil 2"},
		"31" : {"descricao" : "Abandono_Perfil_3", "reason" : "Abandono Perfil 3"},
		"32" : {"descricao" : "Inicio_Perfil_3", "reason" : "Inicio Perfil 3"},
		"33" : {"descricao" : "Opc_Central_Atendimento_Perfil_3", "reason" : "Opcao Central Atendimento Perfil 3"},
		"34" : {"descricao" : "Opc_Assistencia_Perfil_3", "reason" : "Opcao  Assistencia Perfil 3"},
		"35" : {"descricao" : "Opc_Reserva_Restaurante_Perfil_3", "reason" : "Opcao Reserva Restaurante Perfil 3"},
		"36" : {"descricao" : "Repetir _Opcoes_Perfil_3", "reason" : "Repetir _Opcoes_Perfil_3"},
		"37" : {"descricao" : "Opcao_Invalida_Perfil_3", "reason" : "Opcao  Invalida Perfil 3"},
		"38" : {"descricao" : "Tempo_Espera_Excedido_Perfil_3", "reason" : "Tempo Espera Excedido Perfil 3"},
		"39" : {"descricao" : "Abandono_Concierge_Solicitacao_Em_Andamento", "reason" : "Abandono Concierge Solicitacao Em Andamento"},
		"40" : {"descricao" : "Inicio_Concierge_Solicitacao_Em_Andamento", "reason" : "Inicio Concierge Solicitacao Em Andamento"},
		"41" : {"descricao" : "Consultar_Solicitacao_Concierge", "reason" : "Consultar Solicitacao Concierge"},
		"42" : {"descricao" : "Continuar_Menu_Concierge", "reason" : "Continuar Menu Concierge"},
		"43" : {"descricao" : "Abandono_Concierge", "reason" : "Abandono Concierge"},
		"44" : {"descricao" : "Inicio_Concierge", "reason" : "Inicio Concierge"},
		"45" : {"descricao" : "Opc_Solicitar_Agenda_Cultural", "reason" : "Opcao Solicitar Agenda Cultural"},
		"46" : {"descricao" : "Opc_Planejamento_Viagem_Concierge", "reason" : "Opcao Planejamento Viagem Concierger"},
		"47" : {"descricao" : "Opc_Reserva_Restaurante_Concierge", "reason" : "Opcao Reserva Restaurante Concierge"},
		"48" : {"descricao" : "Opc_Compra_Ingressos", "reason" : "Opcao Compra de Ingressos"},
		"49" : {"descricao" : "Opc_Voltar_Menu_Anterior_Concierge", "reason" : "Voltar ao Menu Anterior Concierge"},
		"50" : {"descricao" : "Transferencia_Ope_Concierge", "reason" : "Transferencia Operador Concierge"},
		"51" : {"descricao" : "Repetir_Opcoes_Concierge", "reason" : "Repetir Opcoes Concierge"},
		"52" : {"descricao" : "Opc_Invalida_Concierge", "reason" : "Opcao Invalida Concierge"},
		"53" : {"descricao" : "Tempo_Espera_Excedido_Concierge", "reason" : "Tempo Espera Excedido Concierge"},		
		"54" : {"descricao" : "Abandono_Assistencia", "reason" : "Abandono Assistencia"},
		"55" : {"descricao" : "Inicio_Assistencia", "reason" : "Inicio Assistencia"},
		"56" : {"descricao" : "Opc_Viagem_Schengen_Viagem", "reason" : "Opcao Viagem Schengen Viagem"},
		"57" : {"descricao" : "Opc_Consulta_Sala_VIP_Viagem", "reason" : "Opcao Consulta Sala VIP Viagem"},
		"58" : {"descricao" : "Opc_Voltar_Menu_Anterior_Assistencia", "reason" : "Voltar ao Menu Anterior Assistencia"},
		"59" : {"descricao" : "Repetir_Opcoes_Assistencia", "reason" : "Repetir Opcoes Assistencia"},
		"60" : {"descricao" : "Opcao_Invalida_Assistencia", "reason" : "Opcao Invalida Assistencia"},
		"61" : {"descricao" : "Tempo_Espera_Excedido_Assistencia", "reason" : "Tempo Espera Excedido Assistencia"},
		"62" : {"descricao" : "Abandono_Assistencia_Andamento", "reason" : "Abandono Assistencia em Andamento"},
		"63" : {"descricao" : "Inicio_Assistencia_Andamento", "reason" : "Inicio Assistencia Andamento"},
		"64" : {"descricao" : "Opc_Acomp_Assistencia_Resid_Auto", "reason" : "Opcao Acompanhar Assistencia Residencia e Auto"},
		"65" : {"descricao" : "Opc_Acomp_Assistencia_Medica", "reason" : "Opcao Acompanhar Assistencia Medica"},
		"66" : {"descricao" : "Opc_Acomp_Assistencia_Viagem", "reason" : "Opcao Acompanhar Assistencia Viagem"},
		"67" : {"descricao" : "Opc_Voltar_Menu_Anterior_Assistencia_Andamento", "reason" : "Voltar ao Menu Anterior Assistencia em Andamento"},
		"68" : {"descricao" : "Repetir_Opcoes_Assistencia_Andamento", "reason" : "Repetir Opcoes Assistencia Andamento"},
		"69" : {"descricao" : "Opcao_Invalida_Assistencia_Em_Andamento", "reason" : "Opcao Invalida Assistencia Em Andamento"},
		"70" : {"descricao" : "Tempo_Espera_Excedido_Assistencia_Em_Andamento", "reason" : "Tempo Espera Excedido Assistencia Em Andamento"},
		"71" : {"descricao" : "Abandono_Viagem_Schengen", "reason" : "Abandono Viagem Schengen"},
		"72" : {"descricao" : "Inicio_Viagem_Schengen", "reason" : "Inicio Viagem Schengen"},
		"73" : {"descricao" : "Opc_Saber_Tratado_Viagem_Schengen", "reason" : "Opcao Saber Tratado Viagem Schengen"},
		"74" : {"descricao" : "Opc_Cobertura_Cartão_Schengen_Viagem", "reason" : "Opcao Cobertura Cartao Shengen Viagem"},
		"75" : {"descricao" : "Opc_Impressao_Carta_Schengen", "reason" : "Opcao Impressao Carta Schengen"},
		"76" : {"descricao" : "Opc_Voltar_Menu_Anterior_Viagem_Schengen", "reason" : "Opcao Voltar Menu Anterior Viagem Schengen"},
		"77" : {"descricao" : "Opc_Falar_Atendente_Viagem_Schengen", "reason" : "Opcao Falar Atendente Viagem Schengen"},
		"78" : {"descricao" : "Opc_Ouvir_Novamente_Viagem_Schengen", "reason" : "Opc Ouvir Novamente Viagem Schengen"},
		"79" : {"descricao" : "Opc_Invalida_Viagem_Schengen", "reason" : "Opcao Invalida Viagem Schengen"},
		"80" : {"descricao" : "Tempo_Espera_Excedido_Viagem_Schengen", "reason" : "Tempo Espera Excedido Viagem Schengen"},
		"81" : {"descricao" : "Abandono_Schengen_Info", "reason" : "Abandono Schengen Info"},
		"82" : {"descricao" : "Inicio_Schengen_Info", "reason" : "Inicio Schengen Info"},
		"83" : {"descricao" : "Opc_Impressao_Carta_Schengen_Info", "reason" : "Opcao Impressao Carta Schengen Info"},
		"84" : {"descricao" : "Opc_Cobertura_Cartao_Schengen_Info", "reason" : "Opcao Cobertura Carta Schengen Info"},
		"85" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Info", "reason" : "Opcao Voltar Menu Anterior Schengen Info"},
		"86" : {"descricao" : "Opc_Falar_Atendente_Schengen_Info", "reason" : "Opcao Falar Atendente Schengen Info"},
		"87" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Info", "reason" : "Opcao Ouvir Novamente Schengen Info"},
		"88" : {"descricao" : "Opcao_Invalida_Schengen_Info", "reason" : "Opcao Invalida Schengen Info"},
		"89" : {"descricao" : "Tempo_Espera_Excedido_Schengen_Info", "reason" : "Tempo Espera Excedido Schengen Info"},
		"90" : {"descricao" : "Abandono_Schengen_Amex", "reason" : "Abandono Schengen Amex"},
		"91" : {"descricao" : "Inicio_Schengen_Amex", "reason" : "Inicio Schengen Amex"},
		"92" : {"descricao" : "Opc_Impressao_Carta_Schengen_Amex", "reason" : "Opcao Impressao Cartao Schengen Amex"},
		"93" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Amex", "reason" : "Opcao Voltar Menu Anterior Schengen Amex"},
		"94" : {"descricao" : "Opc_Falar_Atendente_Schengen_Amex", "reason" : "Opcao Voltar Menu Anterior Schengen Amex"},
		"95" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Amex", "reason" : "Opcao Ouvir Novamente Schengen Amex"},
		"96" : {"descricao" : "Opcao_Invalida_Schengen_Amex", "reason" : "Opcao Invalida Schengen Amex"},
		"97" : {"descricao" : "Tempo_Espera_Excedido_Schengen_Amex", "reason" : "Tempo Espera Excedido Schengen Amex"},
		"98" : {"descricao" : "Abandono_Schengen_Site", "reason" : "Abandono Schengen Site"},
		"99" : {"descricao" : "Inicio_Schengen_Site", "reason" : "Inicio Schengen Site"},
		"100" : {"descricao" : "Opc_Cobertura_Cartao_Schengen_Site", "reason" : "Opcao Cobertura Cartao Schengen Site"},
		"101" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Site", "reason" : "Opcao Voltar Menu Anterior Schengen Site"},
		"102" : {"descricao" : "Opc_Falar_Atendente_Schengen_Site", "reason" : "Opcao Falar Atendente Schengen Site"},
		"103" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Site", "reason" : "Opcao Ouvir Novamente Schengen Site"},
		"104" : {"descricao" : "Opcao_Invalida_Schengen_Site", "reason" : "Opcao Invalida Schengen Site"},
		"105" : {"descricao" : "Tempo_Espera_Excedido_Schengen_Site", "reason" : "Tempo Espera Excedido Schengen Site"},
		"106" : {"descricao" : "Inicio_Schengen_Info", "reason" : "Inicio Schengen Info"},
		"107" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Info", "reason" : "Opc_Ouvir_Novamente Schengen Info"},
		"108" : {"descricao" : "Opc_Impressao_Carta_Schengen_Info", "reason" : "Opcao Impressao Carta Schengen Info"},
		"109" : {"descricao" : "Opc_Cobertura_Cartao_Schengen_Info", "reason" : "Opcao Cobertura Carta Schengen Info"},
		"110" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Info", "reason" : "Opcao Voltar Menu Anterior Schengen Info"},
		"111" : {"descricao" : "Opc_Falar_Atendente_Schengen_Info", "reason" : "Opcao Falar Atendente Schengen Info"},
		"112" : {"descricao" : "Opc_Invalida_Schengen_Info", "reason" : "Opcao Invalida Schengen Info"},
		"113" : {"descricao" : "Tempo_Espera_Excedido_Schengen_Info", "reason" : "Tempo Espera Excedido Schengen Info"},
		"114" : {"descricao" : "Abandono_Schengen_Amex", "reason" : "Abandono Schengen Amex"},
		"115" : {"descricao" : "Inicio_Schengen_Amex", "reason" : "Inicio Schengen Amex"},
		"116" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Amex", "reason" : "Opc Ouvir Novamente Schengen Amex"},
		"117" : {"descricao" : "Opc_Impressao_Carta_Schengen_Amex", "reason" : "Opcao Impressao Cartao Schengen Amex"},
		"118" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Amex", "reason" : "Opcao Voltar Menu Anterior Schengen Amex"},
		"119" : {"descricao" : "Opc_Falar_Atendente_Schengen_Amex", "reason" : "Opcao Falar Atendente Schengen Amex"},
		"120" : {"descricao" : "Opc_Invalida_Schengen_Amex", "reason" : "Opcao Invalida Schengen Amex"},
		"121" : {"descricao" : "Tempo_Espera_Excedido_Schengen_Amex", "reason" : "Tempo Espera Excedido Schengen Amex"},
		"122" : {"descricao" : "Abandono_Schengen_Site", "reason" : "Abandono Schengen Site"},
		"123" : {"descricao" : "Inicio_Schengen_Site", "reason" : "Inicio Schengen Site"},
		"124" : {"descricao" : "Opc_Ouvir_Novamente_Schengen_Site", "reason" : "Opc Ouvir Novamente Schengen Site"},
		"125" : {"descricao" : "Opc_Cobertura_Cartao_Schengen_Site", "reason" : "Opcao Cobertura Cartao Schengen Site"},
		"126" : {"descricao" : "Opc_Voltar_Menu_Anterior_Schengen_Site", "reason" : "Opcao Voltar Menu Anterior Schengen Site"},
		"127" : {"descricao" : "Opc_Falar_Atendente_Schengen_Site", "reason" : "Opcao Falar Atendente Schengen Site"},
		"128" : {"descricao" : "Opc_Invalida_Schengen_Site", "reason" : "Opcao Invalida Schengen Site"},
		"129" : {"descricao" : "Tranferencia_Operador_Cartao_Nao_Coletados", "reason" : "Transferencia Operador Por Dados de Cartao Nao Coletados"},
		"130" : {"descricao" : "Abandono_Transferencia", "reason" : "Abandono Transferencia"},
		"131" : {"descricao" : "Inicio_Transferencia", "reason" : "Inicio Transferencia"},
		"132" : {"descricao" : "Opc_Ouvir_Novamente_Transferencia", "reason" : "Opcao Ouvir Novamente Transferencia"},
		"133" : {"descricao" : "Opc_Invalida_Transferencia", "reason" : "Opcao Invalida Transferencia"},
		"134" : {"descricao" : "CVV_Invalido", "reason" : "CVV Invalido"},
		"135" : {"descricao" : "Data_Invalida", "reason" : "Data Invalida"},
		"136" : {"descricao" : "Abandono_Coleta_Cartao_Externa", "reason" : "Abandono Coleta Cartao_Externa"},
		"137" : {"descricao" : "Abandono_Consulta_ID_Sessao", "reason" : "Abandono Consulta ID Sessao"},
		"138" : {"descricao" : "Inicio_Consulta_ID_Sessao", "reason" : "Inicio Consulta ID Sessao"},
		"139" : {"descricao" : "Consulta_ID_Sessao_Com_Sucesso", "reason" : "Consulta ID Sessao com Sucesso"},
		"140" : {"descricao" : "Abandono_Consulta_ID_Sessao", "reason" : "Abandono ID Sessao"},
		"141" : {"descricao" : "Erro_Consulta_ID_Sessao", "reason" : "Erro Consulta ID Sessao"},
		"142" : {"descricao" : "Inicio_Consulta_Bin", "reason" : "Inicio Consulta Bin"},
		"143" : {"descricao" : "Consulta_Bin_Com_Sucesso", "reason" : "Consulta Bin Com Sucesso"},
		"144" : {"descricao" : "Abandono_Consulta_Bin", "reason" : "Abandono Consulta Bin"},
		"145" : {"descricao" : "Erro_Consulta_Bin", "reason" : "Erro Consulta Bin"},
		"146" : {"descricao" : "Abandono Consulta Protocolo", "reason" : "Abandono Consulta Protocolo"},
		"147" : {"descricao" : "Inicio_Consulta_Protocolo", "reason" : "Inicio Consulta Protocolo"},
		"148" : {"descricao" : "Erro_Consulta_Protocolo", "reason" : "Erro Consulta Protocolo"},
		"149" : {"descricao" : "Consulta_Protocolo_Com_Sucesso", "reason" : "Consulta Protocolo Com Sucesso"},
		"150" : {"descricao" : "Abandono_Armazena_Protocolo", "reason" : "Abandono Armazena Protocolo"},
		"151" : {"descricao" : "Inicio_Armazena_Protocolo", "reason" : "Inicio Armazena Protocolo"},
		"152" : {"descricao" : "Armazena_Protocolo_Com_Sucesso", "reason" : "Armazena Protocolo Com Sucesso"},
		"153" : {"descricao" : "Erro_Armazena_Protocolo", "reason" : "Erro Armazena Protocolo"},
		"154" : {"descricao" : "Abandono_Fala_Protocolo", "reason" : "Abandono Fala Protocolo"},
		"155" : {"descricao" : "Inicio_Fala_Protocolo", "reason" : "Inicio Fala Protocolo"},
		"156" : {"descricao" : "Opc_Repetir_Protocolo", "reason" : "Opcao Repetir Protocolo"},
		"157" : {"descricao" : "Fala_Protocolo_Com_Sucesso", "reason" : "Fala Protocolo Com Sucesso"},
		"158" : {"descricao" : "Opcao_Invalida_Fala_Protocolo", "reason" : "Opcao Invalida Fala Protocolo"},
		"159" : {"descricao" : "Abandono_Captura_CVV", "reason" : "Abandono Captura CVV"},
		"160" : {"descricao" : "Inicio_Captura_CVV", "reason" : "Inicio Captura CVV"},
		"161" : {"descricao" : "Captura_CVV_Com_Sucesso", "reason" : "Captura CVV Com Sucesso"},
		"162" : {"descricao" : "Tempo_Espera_Excedido_Captura_CVV", "reason" : "Tempo Espera Excedido Captura CVV"},
		"163" : {"descricao" : "Abandono_Solicita_Expiracao", "reason" : "Abandono Solicita Expiracao"},
		"164" : {"descricao" : "Inicio_Solicita_Expiracao", "reason" : "Inicio Solicita Expiracao"},
		"165" : {"descricao" : "Data_Invalida_Solicita_Expiracao", "reason" : "Data Invalida Solicita Expiracao"},
		"166" : {"descricao" : "Tempo_Espera_Excedido_Solicita_Expiracao", "reason" : "Tempo Espera Excedido Solicita Expiracao"},
		"167" : {"descricao" : "Data_Valida", "reason" : "Data Valida"},
		"168" : {"descricao" : "Abandono_Registra_Cartao_Pagamento", "reason" : "Abandono Registra Cartao Pagamento"},
		"169" : {"descricao" : "Inicio_Registra_Cartao_Pagamento", "reason" : "Inicio Registra Cartao Pagamento"},
		"170" : {"descricao" : "Registra_Cartao_Pagamento_Com_Sucesso", "reason" : "Registra Cartao Pagamento Com Sucesso"},
		"171" : {"descricao" : "Erro_Registra_Cartao_Pagamento", "reason" : "Erro Registra Cartao Pagamento"},
		"172" : {"descricao" : "Abandono_Consulta_Case", "reason" : "Abandono Consulta Case"},
		"173" : {"descricao" : "Inicio_Consulta_Case", "reason" : "Inicio Consulta Case"},
		"174" : {"descricao" : "Consulta_Case_Com_Sucesso", "reason" : "Consulta Case Com Sucesso"},
		"175" : {"descricao" : "Erro_Consulta_Case", "reason" : "Erro Consulta Case"},
		"176" : {"descricao" : "Dados_Do_Cartao_Coletados", "reason" : "Dados do Cartao Coletados"},
		"177" : {"descricao" : "Abandono_Consulta_Braspag", "reason" : "Abandono Consulta Braspag"},
		"178" : {"descricao" : "Inicio_Consulta_Braspag", "reason" : "Inicio Consulta Braspag"},
		"179" : {"descricao" : "Consulta_Braspag_Com_Sucesso", "reason" : "Consulta Braspag Com Sucesso"},
		"180" : {"descricao" : "Erro_Consulta_Braspag", "reason" : "Erro Consulta Braspag"},
		"181" : {"descricao" : "Cartao_Invalido_Braspag", "reason" : "Cartao Invalido Braspag"},
		"182" : {"descricao" : "Braspag_Operation_Successful", "reason" : "Braspag Operation Successful"},
		"183" : {"descricao" : "Braspag_Not_Authorized", "reason" : "Braspag Not Authorized"},
		"184" : {"descricao" : "Braspag_Card_Expired", "reason" : "Braspag Card Expired"},
		"185" : {"descricao" : "Braspag_Blocked_Card", "reason" : "Braspag Blocked Card"},
		"186" : {"descricao" : "Braspag_Timed_Out", "reason" : "Braspag Timed Out"},
		"187" : {"descricao" : "Braspag_Card_Canceled", "reason" : "Braspag Card Canceled"},
		"188" : {"descricao" : "Braspag_Problems_With_Creditcard", "reason" : "Braspag Problems With Creditcard"},
		"189" : {"descricao" : "Braspag_Retorno_Desconhecido", "reason" : "Braspag Retorno Desconhecido"},
		"190" : {"descricao" : "Retorno_Web_Service_Desconhecido_Braspag", "reason" : "Retorno Web Service Desconhecido Braspag"},
		"191" : {"descricao" : "Erro_de_Conexao_Com_Web_Service_Braspag_Conteudo", "reason" : "Erro de Conexao Com Web Service Braspag Conteudo"},
		"192" : {"descricao" : "Tentativas_de_Conexao_Com_Web_Service_Excedidas", "reason" : "Tentativas de Conexao Com Web Service Excedidas"},
		"193" : {"descricao" : "Tentativas_de_Conexao_Com_Web_Service", "reason" : "Tentativas de Conexao Com Web Service"},
		"194" : {"descricao" : "Erro_de_Conexao_Com_Web_Service_Braspag", "reason" : "Erro de Conexao Com Web Service Braspag"},
		"195" : {"descricao" : "Transferencia_Direta_Da_Chamada_Problemas_De_Conexao_Web_Service", "reason" : "Transferencia Direta Da Chamada Problemas De Conexao Web Service"},
		"196" : {"descricao" : "Opc_Concierge_Transferencia_PTS", "reason" : "Opc Concierge Transferencia PTS"},
		"197" : {"descricao" : "Opc_Concierge_Fora_Horario", "reason" : "Opc Concierge Fora Horario"},
		"198" : {"descricao" : "Opc_Concierge_Nao_Platinum", "reason" : "Opc Concierge Nao Platinum"},
		"199" : {"descricao" : "Info e Agradecimento Central Gold Card", "reason" : "Info e Agradecimento Central Gold Card"},
		"200" : {"descricao" : "Central_Atendimento_Platinum", "reason" : "Central de Atendimento Platinum"},
		"201" : {"descricao" : "Erro_Transferencia", "reason" : "Erro Transferencia"},
		"202" : {"descricao" : "Excedeu_Tentativas_Platinum", "reason" : "Excedeu Tentativas Platinum"},
		"203" : {"descricao" : "Excedeu_Tentativas_Nao_Platinum", "reason" : "Excedeu Tentativas Nao Platinum"},
		"204" : {"descricao" : "Erro_Perfil_1", "reason" : "Erro Perfil 1"},
		"205" : {"descricao" : "Total_Erro", "reason" : "Total Erro"},
		"206" : {"descricao" : "Total_Abandono", "reason" : "Total Abandono"},
		"207" : {"descricao" : "Erro_Main", "reason" : "Erro Main"},
		"208" : {"descricao" : "Abandono_Main", "reason" : "Abandono Main"},
		"209" : {"descricao" : "Erro_Perfil_2", "reason" : "Erro Perfil 2"},
		"210" : {"descricao" : "Erro_Perfil_3", "reason" : "Erro Perfil 3"},
		"211" : {"descricao" : "Erro_Menu_Assistencia", "reason" : "Erro Menu Assistencia"},
		"212" : {"descricao" : "Erro_Menu_Assistencia_Em_Andamento", "reason" : "Erro Menu Assistencia Em Andamento"},
		"213" : {"descricao" : "Erro_Concierge", "reason" : "Erro Concierge"},
		"214" : {"descricao" : "Erro_Viagem_Schengen", "reason" : "Erro Viagem Schengen"},
		"215" : {"descricao" : "Erro_Schengen_Info", "reason" : "Erro Schengen Info"},
		"216" : {"descricao" : "Erro_Schengen_Amex", "reason" : "Erro Schengen Amex"},
		"217" : {"descricao" : "Erro_Schengen_Site", "reason" : "Erro Schengen Site"},
		"218" : {"descricao" : "Erro_Usado_Contingencia", "reason" : "Erro Usado Contingencia"},
		"219" : {"descricao" : "Erro_Contingencia_Perfil_1", "reason" : "Erro Contingencia Perfil 1"},
		"220" : {"descricao" : "Erro_Contingencia_Perfil_2", "reason" : "Erro Contingencia Perfil 2"},
		"221" : {"descricao" : "Erro_Contingencia_Perfil_3", "reason" : "Erro Contingencia Perfil 3"},
		"222" : {"descricao" : "Erro_Contingencia_Schengen_Viagem", "reason" : "Erro Contingencia Schengen Viagem"},
		"223" : {"descricao" : "Erro_Contingencia_Assistencia", "reason" : "Erro Contingencia Assistencia"},
		"224" : {"descricao" : "Erro_Contingencia_Concierge", "reason" : "Erro Contingencia Concierge"},
		"225" : {"descricao" : "Erro_Contingencia_Andamento", "reason" : "Erro Contingencia Andamento"},
		"226" : {"descricao" : "Erro_Contingencia_Schengen_Info", "reason" : "Erro Contingencia Schengen Info"},
		"227" : {"descricao" : "Erro_Contingencia_Schengen Amex", "reason" : "Erro Contingencia Schengen Amex"},
		"228" : {"descricao" : "Erro_Contingencia_Schengen Site", "reason" : "Erro Contingencia Schengen Site"},
		"229" : {"descricao" : "Erro_Contingencia_Transferir", "reason" : "Erro Contingencia Transferir"},
		"231" : {"descricao" : "Erro_Contingencia_Finalizar", "reason" : "Erro Contingencia Finalizar"},
		"232" : {"descricao" : "Erro_Contingencia_Abandono", "reason" : "Erro Contingencia Abandono"},
		"233" : {"descricao" : "Erro_Contingencia_Erro", "reason" : "Erro Contingencia Erro"},
		"234" : {"descricao" : "Erro_Contingencia_Nao_Mapeado", "reason" : "Erro Contingencia Nao Mapeado"},
		"235" : {"descricao" : "Erro_Coleta_Dados_Cartao_Externa", "reason" : "Erro Coleta Dados Cartao Externa"},
		"236" : {"descricao" : "Abandono_Coleta_Cartao_Interna", "reason" : "Abandono Coleta Cartao_Interna"},
		"237" : {"descricao" : "Erro_Contingencia_Loop_Infinito", "reason" : "Erro Contingencia Loop Infinito"},
		"238" : {"descricao" : "Erro_Coleta_Cartao_Interna", "reason" : "Erro Coleta Cartao Interna"},
		"239" : {"descricao" : "Erro_Consulta_Bin", "reason" : "Erro Consulta Bin"},
		"240" : {"descricao" : "Erro_Consulta_do_Registra Cartao Pagamento", "reason" : "Erro Consulta do Registra Cartao Pagamento"},
		"241" : {"descricao" : "Erro_Consulta_Id_Sessao", "reason" : "Erro Consulta Id Sessao"},
		"242" : {"descricao" : "Erro_Consulta_Protocolo", "reason" : "Erro Consulta Protocolo"},
		"243" : {"descricao" : "Erro_Consulta_Case", "reason" : "Erro Consulta Case"},
		"244" : {"descricao" : "Erro_Solicita_Expiracao", "reason" : "Erro Solicita Expiracao"},
		"245" : {"descricao" : "Erro_Transforma_Hexa", "reason" : "Erro Transforma Hexa"},
		"246" : {"descricao" : "Abandono_Transforma_Hexa", "reason" : "Abandono Transforma Hexa"},
		"247" : {"descricao" : "Erro_Consulta_Braspag", "reason" : "Erro Consulta Braspag"},
		"248" : {"descricao" : "Opc_Compra_Ingressos_Express_Fun", "reason" : "Opc Compra Ingressos Express Fun"},
		"249" : {"descricao" : "Inicio_Coleta_Cartao_Chamada_Interna", "reason" : "Inicio Coleta Cartao Chamada Interna"},
		"250" : {"descricao" : "Cartao_Invalido", "reason" : "Cartao Invalido"},
		"251" : {"descricao" : "Cartao_Valido", "reason" : "Cartao Valido"},
		"252" : {"descricao" : "Tranferencia_Operador_Cartao_Nao_Coletados", "reason" : "Transferencia Operador Por Dados de Cartao Nao Coletados"},
		"253" : {"descricao" : "Dados_Do_Cartao_Coletados", "reason" : "Dados do Cartao Coletados"},
		"254" : {"descricao" : "Dados_Invalido_do_Cartao_Coletados", "reason" : "Dados Invalido do Cartao Coletados"},
		"255" : {"descricao" : "Erro_na_Contingencia_Loop_Finalizar_Chamada", "reason" : "Ero na Contingencia Loop Finalizar Chamada"},
		"256" : {"descricao" : "Cartao_Valido_Por_Contingencia", "reason" : "Cartao Valido Por Contingencia"},
		"257" : {"descricao" : "Chamada_Desconectada", "reason" : "Chamada Disconectada"},
		"258" : {"descricao" : "Transferencia_Externa", "reason" : "Transferencia Externa"},
		"259" : {"descricao" : "Transferencia_Interna", "reason" : "Transferencia Interna"},
		"260" : {"descricao" : "Seguro_Viagem_Bradesco_Platinum", "reason" : "Seguro Viagem Bradesco Platinum"},
		"261" : {"descricao" : "Seguro_Viagem_BIN_Compartilhado", "reason" : "Seguro Viagem BIN Compartilhado"},
		"262" : {"descricao" : "Seguro_Viagem_Bradesco_Gold", "reason" : "Seguro Viagem Bradesco Gold"},
		"263" : {"descricao" : "Seguro_Viagem_Credit", "reason" : "Seguro Viagem Credit"},
		"264" : {"descricao" : "Seguro_Viagem_Bradesco_Gold_Credit", "reason" : "Seguro Viagem Bradesco Gold Credit"},
		"265" : {"descricao" : "Seguro_Viagem_Bradesco_Credit", "reason" : "Seguro Viagem Bradesco Credit"},
		"266" : {"descricao" : "Seguro_Viagem_Blue", "reason" : "Seguro Viagem Blue"},
		"267" : {"descricao" : "Seguro_Viagem_Platinum_Credit", "reason" : "Seguro Viagem Platinum Credit"},
		"268" : {"descricao" : "Seguro_Viagem_Green", "reason" : "Seguro Viagem Green"},
		"269" : {"descricao" : "Seguro_Viagem_Gold_Credit", "reason" : "Seguro Viagem Gold Credit"},
		"270" : {"descricao" : "Seguro_Viagem_Gold_Card", "reason" : "Seguro Viagem Gold Card"},
		"271" : {"descricao" : "Seguro_Viagem_Platinum_Card", "reason" : "Seguro Viagem Platinum Card"},
		"272" : {"descricao" : "Seguro_Viagem_Cartao_Nao_Mapeado", "reason" : "Seguro Viagem Cartao Nao Mapeado"},
		"273" : {"descricao" : "Seguro_Viagem_Abandono", "reason" : "Seguro Viagem Abandono"},
		"274" : {"descricao" : "Seguro_Viagem_Erro", "reason" : "Seguro Viagem Erro"},
		"275" : {"descricao" : "Seguro_Viagem_Inicio", "reason" : "Seguro Viagem Inicio"},
		"276" : {"descricao" : "Opc_Seguro_Viagem_-_PF1", "reason" : "Opc Seguro Viagem - PF1"},
		"277" : {"descricao" : "Opc_Seguro_Viagem_-_PF2", "reason" : "Opc Seguro Viagem - PF2"},
		"278" : {"descricao" : "Opc_Seguro_Viagem_-_PF3", "reason" : "Opc Seguro Viagem - PF3"}
};

//funcao que retorna um evento
function getEvento(evNum){
	return ev[evNum].descricao;
}

//funcao que retorna um reason
function getReason(reasonNum){
	return ev[reasonNum].reason;
}